name: freshpress
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^5.0.0
  confetti: ^0.8.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.4.0
  hugeicons: ^0.0.11
  iconify_flutter: ^0.0.7
  icons_plus: ^5.0.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  lucide_icons: ^0.257.0
  material_design_icons_flutter: ^7.0.7296
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  #------------------- FONTS ---------------------#
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 600
  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/